language: go

go:
- 1.12.x

env:
  global:
    - PATH="$GOPATH/bin:$PATH"
    - RELEASES_PATH=/tmp/releases

script:
  - go test ./...
  # - golangci-lint run

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Valeriy Soloviov"
  - git config --local user.email "weldpua2008@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG || true

  - go get github.com/laher/goxc
  - goxc -tasks 'xc archive' -bc 'windows darwin linux' -d "$RELEASES_PATH" -resources-include 'README*' -build-ldflags="-X github.com/weldpua2008/supraworker/cmd.GitCommit=${TRAVIS_TAG} " 

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  file:
    - $RELEASES_PATH/snapshot/golog-tools_windows_386.zip
    - $RELEASES_PATH/snapshot/golog-tools_windows_amd64.zip
    - $RELEASES_PATH/snapshot/golog-tools_darwin_386.zip
    - $RELEASES_PATH/snapshot/golog-tools_darwin_amd64.zip
    - $RELEASES_PATH/snapshot/golog-tools_linux_386.tar.gz
    - $RELEASES_PATH/snapshot/golog-tools_linux_amd64.tar.gz
    - $RELEASES_PATH/snapshot/golog-tools_linux_arm.tar.gz
  on:
    repo: weldpua2008/supraworker
    tags: true
    draft: true
